name: CD Deploy SSH
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  job_backend:
    name: Build Back-end
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOSTNAME}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        script: |
          ./update-backend.sh
  job_frontend:
    name: Build Front-end
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOSTNAME}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        script: ./update-frontend.sh
